before_script:
  - gem install rest-client
  - gem install cutest
  - gem install mocha -v 1.1

script:
  - cutest test/localytics_test.rb

deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  on:
    repo: tobuy/localytics-ruby
    branch: master